[tool.poetry]
name = "sloth-auth"
version = "0.1.0"
description = ""
authors = ["lana_remenyuk"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
